### ISSUE TITLE
Redmine 3.4

### ISSUE THREAD

**Issue by Xandrr** [alexbevi/redmine_knowledgebase#363] opened 2018-10-16 09:39 UTC
Hello.
Thank you for this great plugin!
Can you make this compatible with Redmine 3.4? I can see pull request for this, maybe it is a good solution?

**Comment by zoeeer** [comment] 2018-10-27 03:08
Have you tried it with Redmine 3.4? I'm using it on 3.4, and there are only 2 minor problems I found so far:

1. the settings don't work
I can make changes to the settings in the admin panel, but after hitting 'Save' button, every input area becomes blank on the settings page (but I checked the database and see my changes are actually saved).
Also, the changes I made are not effective when using the plugin. It still runs with the default settings.
Currently I'm getting around this by changing default settings in the code

2. the attachements in articles are not shown
already discussed in issue #351 and there's solution there

**Comment by zoeeer** [comment] 2018-10-27 08:56
I just looked into the pull request #359 you mentioned. It just solved the settings problem.
However it seems that the settings incompatibility is caused by a [defect](https://www.redmine.org/issues/28529) of redmine itself. Not sure if it will be fixed later.

**Comment by alexbevi** [comment] 2024-10-05 10:57
This should be addressed by #411

**Closed by alexbevi** 2024-10-05 10:57 UTC
